### ISSUE TITLE
Uses incorrect simulator version

### ISSUE THREAD

**Issue by arobinson** [landonf/simlaunch#12]
I have Xcode 4.2.1 and 4.4.1 installed. My xcode-select is pointing to the xcode 4.4.1 installation. simlaunch is launching my 4.2.1 simulator though.  Even if I move /Developer to /Developer.old, it still runs the simulator in that directory and not the correct one under /Applications/Xcode.app/Contents/Developer.

**Comment by landonf** [comment]
simlaunch automatically discovers all simulator platform SDKs that match the application's requirements. If anyone wants to figure out a reasonable way to prioritize /Applications/Xcode.app over other locations, I'd be happy to accept the patch.
