### ISSUE TITLE
Required iPhone SDK not found

### ISSUE THREAD

**Issue by ghost** [landonf/simlaunch#13]
Hello! I am running on 10.8 and after using Simulator Bundler, when I open the complied app,  I get an error:

The iPhone SDK required by the application could not be found. Please install the iphoneos6.0 SDK and try again.

I have latest XCode installed along with the iOS SDK.  Any help?

**Comment by joehohman** [comment]
Same issue here.  I'm assuming the app needs an update for iOS6 or Mountain Lion. Not sure if the original developers are still working on this project though.

**Comment by landonf** [comment]
Are you running a binary release, or the current git sources? I need to cut a new release, but the current code is working for me on ML.

**Comment by joehohman** [comment]
I'm running a binary.  I tried building it from source with xcode, but

## couldn't get it to build.

Joe Hohman
Development Director
Studio 8e8, Inc.
330.307.1183

**Comment by marciovm** [comment]
I ran into same issue, built from latest git source today. On OS X 10.8.2.

**Comment by landonf** [comment]
Can you provide any relevant messages from the logs? (ie, Console.app)

**Comment by marciovm** [comment]
When I launch the app I see the following on Console.app:

> 12/28/12 10:41:48.553 AM Launcher[943]: Skipping platform discovery result '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform', does not match requirements (mv=1, df=1, es=0)
> 12/28/12 10:41:48.558 AM Launcher[943]: Skipping platform discovery result '/Developer/Platforms/iPhoneSimulator.platform', does not match requirements (mv=1, df=1, es=0)

and the alert:

> _Required iPhone SDK not found._
> The iPhone SDK required by the application could not be found. Please install the iphoneos6.0 SDK and try again.
> _Quit_

**Comment by landonf** [comment]
Perfect, thanks! Did you happen to run the bundler on a device build, instead of a simulator build? Just noticed that the listed SDK is 'iphoneos6.0', which would be a device SDK.

**Comment by marciovm** [comment]
Ah -- that I did. My bad. 

I just ran the bundler on a simulator build and it's working fine. Thanks for the project and support!

**Comment by landonf** [comment]
Woot! Thanks for helping solve the mystery.

**Comment by walsh06** [comment]
Could you clarify the solution to this issue as I dont understand what you mean by "run the bundler on a device build, instead of a simulator build". Im having the same issue and Im not sure how to fix it.

**Comment by marciovm** [comment]
Xcode can build apps for the simulator or for a device. They are different. You want a simulator build for this. You can find simulator builds within the Xcode folder DerivedData, somewhere like /Xcode/DerivedData/<AppName-code>/Build/Products/Debug-iphonesimulator/<AppName>
