### ISSUE TITLE
Cannot luanch Simulator Bundler on Mac OS X 10.8.4

### ISSUE THREAD

**Issue by sunilkr** [landonf/simlaunch#14]
I am not sure what I need to drag to Simulator Bundler; 
an 
iOS Simulator.app (v6.0 Installed with Xcode 4.6.3 in /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications)
or 
iPhone App (.ipa file kept in Download folder)

I tried both and in any case I got the same message:

"Could not read application property list."
"iPhone Simulator.app does not appear to be a valid iPhone application."

**Comment by landonf** [comment]
You need to drag the application bundle built for the simulator target (not an iOS API, not the simulator app itself).
