### ISSUE TITLE
Bundle Data?

### ISSUE THREAD

**Issue by dshanley** [landonf/simlaunch#3]
Just wondering if there's a way or plans to add the feature to bundle the launcher with some of the data after running the app in the Sim.  This was a useful feature of the iPhoneSimulatorExchange app.

**Comment by landonf** [comment]
If someone is interested in adding this feature, we'd be happy to incorporate it. Also, I can't believe this project was written _four_ years ago. I think this is the longest delay I've ever had between reception and response to a bug. Closing out for now.
