### ISSUE TITLE
Lion Support?

### ISSUE THREAD

**Issue by BadPirate** [landonf/simlaunch#7]
Seems that the Application doesn't work at all on 10.7, is there any plan to update it?

Steps to reproduce:
1.  Install on Lion
2.  Drag simulator made binary (test.app) to Simulator Bundler

Expected Result:

Simulator Bundler will launch and bundle app

Actual Result:

Simulator Bundler doesn't seem to accept the file (dragging not allowed)

**Comment by landonf** [comment]
Resolved in the current trunk version
